- import_playbook: general.yaml

- hosts: nodes
  become: yes
  tasks:
    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Wait for API server to become reachable on controller
      ansible.builtin.uri:
        url: https://192.168.56.100:6443/healthz
        method: GET
        status_code: 200
        validate_certs: no
      register: result
      retries: 10
      delay: 10
      until: result.status == 200

    - name: Generate Join Command on controller
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      run_once: true
      changed_when: false
      when: not kubelet_conf.stat.exists

    - name: Join the Kubernetes cluster
      shell: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists
