services:
  model-service:
    image: zorsekil:latest
    container_name: model-service
    environment:
      - MODEL_TAG=v1.0.6-alpha.6
    networks:
      - appnet
    volumes:
      - model_cache:/usr/src/app/model_cache

  app-service:
    image: ghcr.io/remla25-team22/app-service:1.0.7-pre
    container_name: app-service
    ports:
      - "8080:8080"  
    networks:
      - appnet
    depends_on:
      - model-service
    environment:
      - BackendUrl=http://model-service:8080

  prometheus:
    image: prom/prometheus    
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - appnet

networks:
  appnet:

volumes:
  model_cache:
