apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.56.92
          ports:               # <-- add
          - port: 80           # HTTP
            name: http
            targetPort: 8080
          - port: 443          # HTTPS (optional now, handy later)
            name: https
            targetPort: 8443
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
  values:
    global:
      istioNamespace: istio-system

