{
 "title": "service-app dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total reviews",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Incorrect prediction percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "incorrect_prediction_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prediction time / # requests",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prediction_response_times_bucket{le!=\"0.0\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}