ingress:
  enabled: true

app:
  versions:
    - name: v1
      image: ghcr.io/remla25-team22/app-service:v1.0.2
    - name: v2
      image: ghcr.io/remla25-team22/app-service:v1.1.0

model:
  versions:
    - name: v1
      image: ghcr.io/remla25-team22/model-service:1.0.0
    - name: v2
      image: ghcr.io/remla25-team22/model-service:1.0.1

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

  adminUser: admin
  adminPassword: admin
  replicas: 1
  service:
    type: ClusterIP
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus.istio-system.svc.cluster.local:9090
          isDefault: true
          uid: prometheus_ds