ingress: { enabled: true }
mode: mirror
app:
  versions:
    - name: v1
      image: ghcr.io/remla25-team22/app-service:1.1.7-pre
      weight: 100

model:
  mode: mirror
  versions:
    - name: v1
      image: ghcr.io/remla25-team22/model-service:1.0.16-pre
      modeltag: v1.0.6-alpha.6
    - name: v2
      image: ghcr.io/remla25-team22/model-service:1.0.16-pre
      modeltag: v1.0.7
