apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.56.92
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
  values:
    global:
      istioNamespace: istio-system
