- hosts: all
  become: yes
  tasks:
    - name: Disable swap
      shell: swapoff -a

    - name: Remove swap from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        state: absent

    - name: Load required kernel modules for future reboots
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules now
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: Apply sysctl settings
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.ipv4.ip_forward', value: 1 }
        - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }

    - name: Register student SSH keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../ssh_keys/*.pub"

    - name: Generate /etc/hosts from template
      template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
