- import_playbook: general.yaml
- hosts: nodes
  become: yes
  tasks:
    - name: Get kubeadm join command from controller
      shell: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_command
      changed_when: false

    - name: Join the Kubernetes cluster
      shell: "{{ join_command.stdout }}"
      args:
        warn: false
      when: "'This node has joined the cluster' not in join_command.stdout"
