apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-service
spec:
  hosts:
    - app.local
  gateways:
    - app-gateway

{{- if eq .Values.mode "canary" }}
  http:
    # 1. Clients that already carry exp=canary -> always v2
    - match:
        - headers:
            cookie:
              regex: ".*exp=canary.*"
      route:
        - destination:
            host: app-service
            subset: v2
          weight: 100

    # 2. Everyone else → baseline v1
    - route:
        - destination:
            host: app-service
            subset: v1
          weight: 100

{{- else }}
  http:
    - route:
        - destination:
            host: app-service      # no subset, so v1 and v2 pods are both eligible
{{- end }}

