apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"  # Make sure your app exposes /metrics on this port
spec:
  selector:
    app: app-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
