name: Auto Tag, Release, and Bump (with PR)

on:
  push:
    branches:
      - main

jobs:
  tag_and_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Read current version from VERSION.txt
        id: version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Current version: $VERSION"

          # Check if tag already exists
          if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
            echo "Tag $VERSION already exists. Skipping."
            exit 0
          fi

          # Create and push tag
          git tag $VERSION
          git push origin $VERSION

      - name: Bump to next patch version
        run: |
          VERSION=$(cat VERSION.txt)
          IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION#v}"
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="v${MAJOR}.${MINOR}.${NEXT_PATCH}"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "$NEXT_VERSION" > VERSION.txt

      - name: Create pull request for version bump
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Bump to ${{ env.NEXT_VERSION }} after release"
          branch: version-bump
          title: "Bump version to ${{ env.NEXT_VERSION }}"
          body: |
            This PR bumps the version in `VERSION.txt` to `${{ env.NEXT_VERSION }}` after the latest release.
