      - name: Bump to next patch version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "Previous version: $VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION#v}"
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="v${MAJOR}.${MINOR}.${NEXT_PATCH}"

          echo "Bumping to $NEXT_VERSION"
          echo "$NEXT_VERSION" > VERSION.txt

          git add VERSION.txt
          git commit -m "Bump to $NEXT_VERSION after release $VERSION"
          git push origin main
