name: Auto Bump Version After Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Bump to next patch pre-release
        run: |
          VERSION="${GITHUB_REF_NAME#v}"       
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}-pre"

          echo "Bumping version to $NEXT_VERSION"
          echo "$NEXT_VERSION" > VERSION.txt

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add VERSION.txt
          git commit -m "Bump to $NEXT_VERSION after release $VERSION"
          git push origin main